#!/bin/sh

create_table() {
sqlite3 bodacc.db << EOF
CREATE TABLE annonces (ID INT PRIMARY KEY NOT NULL, PARUTION TEXT, NUMERO TEXT, DATE TEXT, CODEPOSTAL INT, VILLE TEXT, NATURE TEXT, RCS INT, TYPE TEXT, FORMEJURIDIQUE TEXT, PREVIOUS INT);
CREATE TABLE geocodes (CODE INT PRIMARY KEY NOT NULL, NOM TEXT);
CREATE TABLE effectifs (CODE TEXT PRIMARY KEY NOT NULL, NOM TEXT);
CREATE TABLE codesnaf (CODE TEXT PRIMARY KEY NOT NULL, LABEL TEXT);
CREATE TABLE categoriesjuridiques (CODE TEXT PRIMARY KEY NOT NULL, LABEL TEXT);
CREATE TABLE uniteslegales(SIREN INT PRIMARY KEY NOT NULL, NOM TEXT, EFFECTIFS TEXT, ACTIVITE TEXT, CATEGORIEJURIDIQUE TEXT, NOMENCLATUREACTIVITE TEXT);
CREATE TABLE etablissements (SIRET BIGINT PRIMARY KEY NOT NULL,SIREN INT,ETATADMIN TEXT,EFFECTIFS TEXT,CP TEXT,VILLE TEXT,NOM TEXT,PAYS TEXT,VILLEETRANGER TEXT,ACTIVITE TEXT, NOMENCLATUREACTIVITE TEXT);
.quit
EOF
}

if [ ! -f bodacc.db ]; then 
create_table
fi