
#!/bin/sh
sqlite3 bodacc.db << EOF
CREATE TABLE annonces (ID INT PRIMARY KEY NOT NULL, NUMERO TEXT, DATE TEXT, ADDRESS TEXT, NATURE TEXT, RCS TEXT, TYPE TEXT, PREVIOUS TEXT, COMPLEMENT TEXT);
.quit
EOF