#!/bin/sh
if [! -f bodacc.db ]; then 
create_table
fi

create_table() {
sqlite3 bodacc.db << EOF
CREATE TABLE annonces (ID INT PRIMARY KEY NOT NULL, PARUTION INT, NUMERO INT, DATE TEXT, CODEPOSTAL INT, VILLE TEXT, NATURE TEXT, RCS INT, TYPE TEXT, FORMEJURIDIQUE TEXT, PREVIOUS INT);
CREATE TABLE etablissements (SIRET BIGINT PRIMARY KEY NOT NULL, SIREN INT, ETATADMIN TEXT,EFFECTIFS TEXT,CP TEXT,CP2 TEXT,VILLE1 TEXT,VILLE2 TEXT,NOM TEXT,PAYS1 TEXT,PAYS2 TEXT,VILLEETRANGER1 TEXT,VILLEETRANGER2 TEXT,ACTIVITE TEXT);
CREATE TABLE geocodes (CODE INT PRIMARY KEY NOT NULL, NOM TEXT);
CREATE TABLE uniteslegales(SIREN INT PRIMARY KEY NOT NULL, NOM TEXT);
.quit
EOF
}